spring:
  # H2 Database ??
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost/~/test'   # H2 DB ?? ?? (In-Memory Mode)
    username: sa        # H2 DB ?? ID (??? ??)
    password:           # H2 DB ?? PW (??? ??)

  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??

  jpa:
    hibernate:
      ddl-auto: create